services:
  - type: web
    name: trnn-bull
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install --prefix restforja
    startCommand: npm start --prefix restforja
    healthCheckPath: /status
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NODE_ENV
        value: production
